import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { MenuProvider } from "@/contexts/MenuContext";
import LoggedInMenuBar from "@/components/LoggedInMenuBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "PB Game Gen",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <MenuProvider>
          <LoggedInMenuBar />
          {children}
        </MenuProvider>
      </body>
    </html>
  );
}
